# Generated by Django 4.2.30 on 2026-04-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Smart Mandi', max_length=200)),
                ('hero_text', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('highlight_one', models.CharField(max_length=255)),
                ('highlight_two', models.CharField(max_length=255)),
                ('highlight_three', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
