# Generated by Django 6.0.1 on 2026-03-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandilocation',
            name='state',
            field=models.CharField(default='Gujarat', max_length=100),
        ),
    ]
