# Generated by Django 4.2.30 on 2026-04-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_finder', '0002_alter_mandilocation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandilocation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
