# Generated by Django 4.2.30 on 2026-04-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_finder', '0003_alter_mandilocation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandilocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
